export default defineAppConfig({
  ui: {
    colors: {
      primary: 'sunflower-gold',
      neutral: 'onyx',
      success: 'jungle-teal',
      info: 'smart-blue',
      error: 'bubblegum-pink'
    },

    icons: {
      arrowDown: 'solar:alt-arrow-down-linear',
      arrowLeft: 'solar:alt-arrow-left-linear',
      arrowRight: 'solar:alt-arrow-right-linear',
      arrowUp: 'solar:alt-arrow-up-linear',
      caution: 'solar:danger-triangle-linear',
      check: 'solar:check-circle-linear',
      chevronDoubleLeft: 'solar:double-alt-arrow-left-linear',
      chevronDoubleRight: 'solar:double-alt-arrow-right-linear',
      chevronDown: 'solar:alt-arrow-down-bold',
      chevronLeft: 'solar:alt-arrow-left-bold',
      chevronRight: 'solar:alt-arrow-right-bold',
      chevronUp: 'solar:alt-arrow-up-bold',
      close: 'solar:close-circle-linear',
      copy: 'solar:copy-linear',
      copyCheck: 'solar:copy-bold',
      dark: 'solar:moon-outline',
      drag: 'solar:transfer-horizontal-linear',
      ellipsis: 'solar:menu-dots-bold',
      error: 'solar:danger-triangle-bold',
      external: 'solar:square-bottom-up-linear',
      eye: 'solar:eye-linear',
      eyeOff: 'solar:eye-closed-linear',
      file: 'solar:file-linear',
      folder: 'solar:folder-linear',
      folderOpen: 'solar:folder-open-linear',
      hash: 'solar:hashtag-linear',
      info: 'solar:info-circle-linear',
      light: 'solar:sun-linear',
      loading: 'svg-spinners:ring-resize',
      menu: 'solar:hamburger-menu-linear',
      minus: 'solar:minus-circle-linear',
      panelClose: 'solar:close-square-linear',
      panelOpen: 'solar:add-square-linear',
      plus: 'solar:add-circle-linear',
      reload: 'solar:refresh-linear',
      search: 'solar:rounded-magnifer-linear',
      stop: 'solar:stop-linear',
      success: 'solar:check-circle-linear',
      system: 'solar:monitor-linear',
      tip: 'solar:lightbulb-minimalistic-linear',
      upload: 'solar:upload-linear',
      warning: 'solar:danger-triangle-linear'
    }
  }
})
